import { MigrationInterface, QueryRunner } from "typeorm";

export class CarListingMigration11742318528685 implements MigrationInterface {
    name = 'CarListingMigration11742318528685'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP CONSTRAINT "FK_5aff4832a05f43e2ac419549b22"`);
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP CONSTRAINT "FK_133a2c06cf107a5c192f8b3506c"`);
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP CONSTRAINT "FK_2879dc8591a6710d79ea371200d"`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" DROP CONSTRAINT "FK_3101a0eb291fd180eddcfb3c62c"`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" DROP CONSTRAINT "FK_cc9b6756dddebcfb08e4e6da5d1"`);
        await queryRunner.query(`ALTER TABLE "car_listing_images" DROP CONSTRAINT "FK_1d215ade387a08e1d6d4ffe15da"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_b39c86a18ed8c61e9d589b93767"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_63762118b10652c6a02ff50096d"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_35583cb7a6a02afc1e341514fdc"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_9574e2bdce7a704f44ee896b838"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_25a4f244613943cc2ff4aabc4a4"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_314233123204c0b9439048ac82c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2ba47d52054e3f1714ce1d822"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d215ade387a08e1d6d4ffe15d"`);
        await queryRunner.query(`ALTER TABLE "car_listing_images" RENAME COLUMN "listingId" TO "listing_id"`);
        await queryRunner.query(`CREATE TABLE "car_variant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "model_id" uuid NOT NULL, "make_id" uuid NOT NULL, "year_id" uuid NOT NULL, CONSTRAINT "PK_e2b2123d0663eae533caae1f116" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a2385755d9b85e787c48749561" ON "car_variant" ("year_id", "name") `);
        await queryRunner.query(`CREATE TABLE "car_year" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "year" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "model_id" uuid NOT NULL, "make_id" uuid NOT NULL, CONSTRAINT "PK_dfac3e25c41ac0dc9b120e94168" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8d8792c2a5d73713cbec2403f2" ON "car_year" ("model_id", "year") `);
        await queryRunner.query(`CREATE TABLE "car_model" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "image_url" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "make_id" uuid NOT NULL, CONSTRAINT "PK_525071eea12c671d67e35a5cbc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_be3f1770d368f51b93ed5a57e9" ON "car_model" ("make_id", "name") `);
        await queryRunner.query(`CREATE TABLE "car_make" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "image_url" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_906716db045c27f467d1b68d7b7" UNIQUE ("name"), CONSTRAINT "PK_cbde9642093e4051e40d9d352a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP COLUMN "modelId"`);
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP COLUMN "makeId"`);
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP COLUMN "yearId"`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" DROP COLUMN "listingId"`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" DROP COLUMN "featureId"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "variantId"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "makeId"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "modelId"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "yearId"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "registrationCityId"`);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD "model_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD "make_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD "year_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" ADD "listing_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" ADD "feature_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "variant_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "make_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "model_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "year_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "registration_city_id" uuid NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_612749a5504b3ec863bbbf2a44" ON "car_listing_features" ("listing_id", "feature_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9627c9ba9f9315a0fb71dd3fb5" ON "car_listing_images" ("listing_id") `);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD CONSTRAINT "FK_827cd95a32e4cfaa40ea12b5eab" FOREIGN KEY ("model_id") REFERENCES "car_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD CONSTRAINT "FK_b43863342e470365066c5626bb0" FOREIGN KEY ("make_id") REFERENCES "car_make"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD CONSTRAINT "FK_708b323941b20699824be6862db" FOREIGN KEY ("year_id") REFERENCES "car_year"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_variant" ADD CONSTRAINT "FK_6991e095a3b5f86ace4aa8f3eb3" FOREIGN KEY ("model_id") REFERENCES "car_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_variant" ADD CONSTRAINT "FK_3ebeaa3e6407e9c32dbd3a24a4c" FOREIGN KEY ("make_id") REFERENCES "car_make"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_variant" ADD CONSTRAINT "FK_f621d1e9cb27cba74ba4f6a5a5a" FOREIGN KEY ("year_id") REFERENCES "car_year"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_year" ADD CONSTRAINT "FK_3469b026b7bad0c9107de0e2a1c" FOREIGN KEY ("model_id") REFERENCES "car_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_year" ADD CONSTRAINT "FK_38d966ed9bd40ce2c6cb3a75c43" FOREIGN KEY ("make_id") REFERENCES "car_make"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_model" ADD CONSTRAINT "FK_e909add875e743f5787a10826a9" FOREIGN KEY ("make_id") REFERENCES "car_make"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" ADD CONSTRAINT "FK_74d7c21ac7b9f49bd4a387370ae" FOREIGN KEY ("listing_id") REFERENCES "car_listings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" ADD CONSTRAINT "FK_b3ba2d5e0da5511578f471e8724" FOREIGN KEY ("feature_id") REFERENCES "available_features"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listing_images" ADD CONSTRAINT "FK_9627c9ba9f9315a0fb71dd3fb54" FOREIGN KEY ("listing_id") REFERENCES "car_listings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_b861b19870468a85c786faa4675" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_2ffb238cfe4a5884e34e5eb27f9" FOREIGN KEY ("variant_id") REFERENCES "car_variant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_56eafd67c3e45e8f0fc3a073ff9" FOREIGN KEY ("make_id") REFERENCES "car_make"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_508d714c6d54cecd2795ef89737" FOREIGN KEY ("model_id") REFERENCES "car_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_3cbb256c8e0368b90f08559aebf" FOREIGN KEY ("year_id") REFERENCES "car_year"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_1e6830d2dc7ad1bfaffd541b99e" FOREIGN KEY ("registration_city_id") REFERENCES "registration_cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_1e6830d2dc7ad1bfaffd541b99e"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_3cbb256c8e0368b90f08559aebf"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_508d714c6d54cecd2795ef89737"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_56eafd67c3e45e8f0fc3a073ff9"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_2ffb238cfe4a5884e34e5eb27f9"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP CONSTRAINT "FK_b861b19870468a85c786faa4675"`);
        await queryRunner.query(`ALTER TABLE "car_listing_images" DROP CONSTRAINT "FK_9627c9ba9f9315a0fb71dd3fb54"`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" DROP CONSTRAINT "FK_b3ba2d5e0da5511578f471e8724"`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" DROP CONSTRAINT "FK_74d7c21ac7b9f49bd4a387370ae"`);
        await queryRunner.query(`ALTER TABLE "car_model" DROP CONSTRAINT "FK_e909add875e743f5787a10826a9"`);
        await queryRunner.query(`ALTER TABLE "car_year" DROP CONSTRAINT "FK_38d966ed9bd40ce2c6cb3a75c43"`);
        await queryRunner.query(`ALTER TABLE "car_year" DROP CONSTRAINT "FK_3469b026b7bad0c9107de0e2a1c"`);
        await queryRunner.query(`ALTER TABLE "car_variant" DROP CONSTRAINT "FK_f621d1e9cb27cba74ba4f6a5a5a"`);
        await queryRunner.query(`ALTER TABLE "car_variant" DROP CONSTRAINT "FK_3ebeaa3e6407e9c32dbd3a24a4c"`);
        await queryRunner.query(`ALTER TABLE "car_variant" DROP CONSTRAINT "FK_6991e095a3b5f86ace4aa8f3eb3"`);
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP CONSTRAINT "FK_708b323941b20699824be6862db"`);
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP CONSTRAINT "FK_b43863342e470365066c5626bb0"`);
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP CONSTRAINT "FK_827cd95a32e4cfaa40ea12b5eab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9627c9ba9f9315a0fb71dd3fb5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_612749a5504b3ec863bbbf2a44"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "registration_city_id"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "year_id"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "model_id"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "make_id"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "variant_id"`);
        await queryRunner.query(`ALTER TABLE "car_listings" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" DROP COLUMN "feature_id"`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" DROP COLUMN "listing_id"`);
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP COLUMN "year_id"`);
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP COLUMN "make_id"`);
        await queryRunner.query(`ALTER TABLE "showroom_details" DROP COLUMN "model_id"`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "registrationCityId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "yearId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "modelId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "makeId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "variantId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" ADD "featureId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" ADD "listingId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD "yearId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD "makeId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD "modelId" uuid NOT NULL`);
        await queryRunner.query(`DROP TABLE "car_make"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be3f1770d368f51b93ed5a57e9"`);
        await queryRunner.query(`DROP TABLE "car_model"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d8792c2a5d73713cbec2403f2"`);
        await queryRunner.query(`DROP TABLE "car_year"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2385755d9b85e787c48749561"`);
        await queryRunner.query(`DROP TABLE "car_variant"`);
        await queryRunner.query(`ALTER TABLE "car_listing_images" RENAME COLUMN "listing_id" TO "listingId"`);
        await queryRunner.query(`CREATE INDEX "IDX_1d215ade387a08e1d6d4ffe15d" ON "car_listing_images" ("listingId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e2ba47d52054e3f1714ce1d822" ON "car_listing_features" ("featureId", "listingId") `);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_314233123204c0b9439048ac82c" FOREIGN KEY ("registrationCityId") REFERENCES "registration_cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_25a4f244613943cc2ff4aabc4a4" FOREIGN KEY ("yearId") REFERENCES "car_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_9574e2bdce7a704f44ee896b838" FOREIGN KEY ("modelId") REFERENCES "car_models"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_35583cb7a6a02afc1e341514fdc" FOREIGN KEY ("makeId") REFERENCES "car_makes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_63762118b10652c6a02ff50096d" FOREIGN KEY ("variantId") REFERENCES "car_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listings" ADD CONSTRAINT "FK_b39c86a18ed8c61e9d589b93767" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listing_images" ADD CONSTRAINT "FK_1d215ade387a08e1d6d4ffe15da" FOREIGN KEY ("listingId") REFERENCES "car_listings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" ADD CONSTRAINT "FK_cc9b6756dddebcfb08e4e6da5d1" FOREIGN KEY ("featureId") REFERENCES "available_features"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_listing_features" ADD CONSTRAINT "FK_3101a0eb291fd180eddcfb3c62c" FOREIGN KEY ("listingId") REFERENCES "car_listings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD CONSTRAINT "FK_2879dc8591a6710d79ea371200d" FOREIGN KEY ("yearId") REFERENCES "car_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD CONSTRAINT "FK_133a2c06cf107a5c192f8b3506c" FOREIGN KEY ("makeId") REFERENCES "car_makes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showroom_details" ADD CONSTRAINT "FK_5aff4832a05f43e2ac419549b22" FOREIGN KEY ("modelId") REFERENCES "car_models"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
